######
#
# Cleaning Makefile
#
######

clean:: ; rm -f *~
clean:: ; rm -f *_dats.o
clean:: ; rm -f *_dats.c

cleanall:: clean
cleanall:: ; rm -f tree_dats
cleanall:: ; rm -f bfs_dats
cleanall:: ; rm -f dfs_dats

###### end of [Makefile] ######
